import React, { useMemo } from "react";
import Head from "next/head";
import Image from "next/image";
import webbuilding from "../public/oishipaginaenconstruccion.jpeg";
import webbuildingm from "../public/oishipaginaenconstruccionm.jpeg";

export default function Home() {
  const [isMobile, setIsMobile] = React.useState(false);
  // const background = useMemo(
  //   () => window.innerWidth >= 375 && setIsMobile(true),
  // );

  React.useEffect(() => {
    window.innerWidth <= 640 && setIsMobile(true);
  }, []);

  return (
    <div>
      <Head>
        <title>Oishi.pe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isMobile ? (
        <Image
          src={webbuildingm}
          alt="Oishi web, pagina en construccion"
          layout="fill"
        />
      ) : (
        <Image
          src={webbuilding}
          alt="Oishi web, pagina en construccion"
          layout="fill"
        />
      )}
    </div>
  );
}
