/* eslint-disable @next/next/no-page-custom-font */
import React, { useMemo } from "react";
import Head from "next/head";
import Image from "next/image";
import oishilogo from "../public/oishisushibar.svg";
import buildingsite from "../public/buildingsite.svg";
import { ImWhatsapp } from "react-icons/im";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Oishi.pe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Andika+New+Basic:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <div className="flex flex-col bg-gray-50 h-screen">
        <div className="px-24 sm: mt-4 sm:flex sm:justify-center">
          <Image
            src={oishilogo}
            alt="Picture of the author"
            width={300}
            height={100}
          />
        </div>
        <div className="flex flex-col sm:flex-row-reverse sm:px-8">
          <div className="px-5 mt-8">
            <Image
              src={buildingsite}
              alt="Picture of the author"
              className="shadow-md"
            />
          </div>
          <div className="px-5 mt-5 sm:mt-24">
            <h1 className="text-4xl sm:text-5xl font-bold font-oishi">
              Pagina Web en construcción
            </h1>
            <h1 className="text-2xl  font-oishi text-gray-600 -mt-1">
              Estamos construyendo una web para ti!
            </h1>
            <div className="mt-3 sm:mt-20 font-oishi text-lg text-gray-700">
              <h2 className="mt-5 mb-2">Mientras puedes pedir por whatsapp</h2>
              <div className="flex flex-wrap items-center ">
                <ImWhatsapp color="green" />
                <h4 className="ml-1">
                  Cañete - <span className="font-bold">992677701</span>
                </h4>
              </div>
              <div className="flex flex-wrap items-center ">
                <ImWhatsapp color="green" />
                <h4 className="ml-1">
                  Ica - <span className="font-bold">992701783</span>
                </h4>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
